In [105]:
# Define the documents as a dictionary where keys are document titles and values are document content
documents = {
    "Article: Pandas Basics": "This article covers the basics of using Pandas in Python.",
    "Tutorial: Data Visualization": "Learn about data visualization techniques with Python libraries.",
    "Case Study: Sales Analysis": "Analyze sales data using Python for a real-world case study."
}


for keys, values in documents.items():
    print(values)

This article covers the basics of using Pandas in Python.
Learn about data visualization techniques with Python libraries.
Analyze sales data using Python for a real-world case study.


In [48]:
# get the keys of the documents and store it in the list
# key_documents = {key for doc in documents for key in doc.split(",")}
key_documents = list(documents.keys())

# display the list of the key documents
print(key_documents)

['Article: Pandas Basics', 'Tutorial: Data Visualization', 'Case Study: Sales Analysis']


In [49]:
# Extract the category of the key documents and store it 
# category = {cat for key in key_documents for cat in key.split(":")}
category = []
for key in key_documents:
    category.append(key.split(':')[0])
    
print(category)

['Article', 'Tutorial', 'Case Study']


In [35]:

# Extract the content values and put them in a list
document_content_list = list(documents.values())

# Display the list of document content
print(document_content_list)

['This article covers the basics of using Pandas in Python.', 'Learn about data visualization techniques with Python libraries.', 'Analyze sales data using Python for a real-world case study.']


In [53]:
# Gather the set of all unique terms from the list content of document and diplay the result
unique_terms = []
for doc in document_content_list:
        terms = list(doc.split())
        for term in terms:
                unique_terms.append(term)

# unique_terms = {term for doc in document_content_list for term in doc.split()}
unique_terms

['This',
 'article',
 'covers',
 'the',
 'basics',
 'of',
 'using',
 'Pandas',
 'in',
 'Python.',
 'Learn',
 'about',
 'data',
 'visualization',
 'techniques',
 'with',
 'Python',
 'libraries.',
 'Analyze',
 'sales',
 'data',
 'using',
 'Python',
 'for',
 'a',
 'real-world',
 'case',
 'study.']

In [38]:
# create a matrix for the document by using the unique term
doc_term_matrix = {}

# your code here
for term in unique_terms:
    doc_term_matrix[term] = []

    for doc in document_content_list:
        if term in doc:
            doc_term_matrix[term].append(1)
        else: doc_term_matrix[term].append(0)

# display the result of the matrix
doc_term_matrix

{'of': [1, 0, 0],
 'Pandas': [1, 0, 0],
 'about': [0, 1, 0],
 'with': [0, 1, 0],
 'Python.': [1, 0, 0],
 'a': [1, 1, 1],
 'data': [0, 1, 1],
 'sales': [0, 0, 1],
 'using': [1, 0, 1],
 'the': [1, 0, 0],
 'case': [0, 0, 1],
 'libraries.': [0, 1, 0],
 'article': [1, 0, 0],
 'in': [1, 0, 1],
 'for': [0, 0, 1],
 'study.': [0, 0, 1],
 'Python': [1, 1, 1],
 'visualization': [0, 1, 0],
 'techniques': [0, 1, 0],
 'Analyze': [0, 0, 1],
 'This': [1, 0, 0],
 'real-world': [0, 0, 1],
 'Learn': [0, 1, 0],
 'basics': [1, 0, 0],
 'covers': [1, 0, 0]}

In [108]:
# import the numpy library if it doesn't work you need to install numpy
import numpy as np

docs_array = np.array(document_content_list, dtype='object')
# docs_arrays = np.array(documents)
print(docs_array)

v1 = np.array(doc_term_matrix['the'])    
v2 = np.array(doc_term_matrix['Python'])

print(v1)
print(v2)
print('-------')

# find the documents that have both terms from v1 and v2
v3 = v1 & v2

print(v3)

# display the content document from the result
# [doc for doc in v3 * docs_array if doc]
result = list(doc for doc in v3 * docs_array if doc)
print(result)

# display the title of the document
# [doc.keys() for doc in v3 * docs_arrays]
# print(docs_arrays.size)
[key.split(':')[1] for key, val in documents.items() for res in result if (res == val)]
# for key,val in documents.items():
#     for res in result:
#         if res == val:
#             print(key.split(':')[1])


['This article covers the basics of using Pandas in Python.'
 'Learn about data visualization techniques with Python libraries.'
 'Analyze sales data using Python for a real-world case study.']
[1 0 0]
[1 1 1]
-------
[1 0 0]
['This article covers the basics of using Pandas in Python.']


[' Pandas Basics']

In [42]:
# find the document for those have at least one word
# import the numpy library if it doesn't work you need to install numpy
import numpy as np

docs_array = np.array(document_content_list, dtype='object')

v1 = np.array(doc_term_matrix['the'])    
v2 = np.array(doc_term_matrix['Python'])

print(v1)
print(v2)
print('-------')

# find the documents that have both terms from v1 and v2
v3 = v1 | v2

print(v3)

# display the content document from the result
[doc for doc in v3 * docs_array if doc]

[1 0 0]
[1 1 1]
-------
[1 1 1]


['This article covers the basics of using Pandas in Python.',
 'Learn about data visualization techniques with Python libraries.',
 'Analyze sales data using Python for a real-world case study.']