In [3]:
import pandas as pd
df = pd.read_csv('tdoc.csv', header=None, names=['Title', 'Content'])
pd.options.display.colheader_justify = "center"
print(df.to_string())



     Title                               Content                           
0  Document 1           This is the first document. It contains some words.
1  Document 2  The second document is a bit longer and has different words.
2  Document 3  The third document is short. Short documents can be concise.


In [4]:
for index, row in df.iterrows():
    print(row)

Title                                             Document 1
Content    This is the first document. It contains some w...
Name: 0, dtype: object
Title                                             Document 2
Content    The second document is a bit longer and has di...
Name: 1, dtype: object
Title                                             Document 3
Content    The third document is short. Short documents c...
Name: 2, dtype: object


In [5]:
key_documents = list(df["Title"])

# Print the extracted rows
print(key_documents)

['Document 1', 'Document 2', 'Document 3']


In [6]:
content = list(df["Content"])

# Print the extracted rows
content

['This is the first document. It contains some words.',
 'The second document is a bit longer and has different words.',
 'The third document is short. Short documents can be concise.']

In [7]:
# unique_term = {term for doc in content for term in doc.split()}
unique_terms = []
for doc in content:
    terms = doc.split()
    for term in terms:
        unique_terms.append(term)

unique_terms

['This',
 'is',
 'the',
 'first',
 'document.',
 'It',
 'contains',
 'some',
 'words.',
 'The',
 'second',
 'document',
 'is',
 'a',
 'bit',
 'longer',
 'and',
 'has',
 'different',
 'words.',
 'The',
 'third',
 'document',
 'is',
 'short.',
 'Short',
 'documents',
 'can',
 'be',
 'concise.']

In [77]:
df2 = pd.DataFrame(unique_terms)


df2.to_csv("tdoc2.csv", header=False, index=False)

In [11]:
doc_term_matrix = {}

# your code here
for term in unique_terms:
    doc_term_matrix[term] = []

    for doc in content:
        # print(doc)
        if term in doc:
            doc_term_matrix[term].append(1)
        else: doc_term_matrix[term].append(0)

# display the result of the matrix
doc_term_matrix

{'This': [1, 0, 0],
 'is': [1, 1, 1],
 'the': [1, 0, 0],
 'first': [1, 0, 0],
 'document.': [1, 0, 0],
 'It': [1, 0, 0],
 'contains': [1, 0, 0],
 'some': [1, 0, 0],
 'words.': [1, 1, 0],
 'The': [0, 1, 1],
 'second': [0, 1, 0],
 'document': [1, 1, 1],
 'a': [1, 1, 1],
 'bit': [0, 1, 0],
 'longer': [0, 1, 0],
 'and': [0, 1, 0],
 'has': [0, 1, 0],
 'different': [0, 1, 0],
 'third': [0, 0, 1],
 'short.': [0, 0, 1],
 'Short': [0, 0, 1],
 'documents': [0, 0, 1],
 'can': [0, 0, 1],
 'be': [0, 0, 1],
 'concise.': [0, 0, 1]}

In [13]:
# import the numpy library if it doesn't work you need to install numpy
import numpy as np

docs_array = np.array(content, dtype='object')
# docs_arrays = np.array(documents)
print(docs_array)

v1 = np.array(doc_term_matrix['the'])    
v2 = np.array(doc_term_matrix['document'])

print(v1)
print(v2)
print('-------')

# find the documents that have both terms from v1 and v2
v3 = v1 & v2

print(v3)

# display the content document from the result
[doc for doc in v3 * docs_array if doc]
# result = list(doc for doc in v3 * docs_array if doc)
# print(result)

# display the title of the document
# [doc.keys() for doc in v3 * docs_arrays]

['This is the first document. It contains some words.'
 'The second document is a bit longer and has different words.'
 'The third document is short. Short documents can be concise.']
[1 0 0]
[1 1 1]
-------
[1 0 0]


['This is the first document. It contains some words.']

In [14]:
# find the document for those have at least one word
# import the numpy library if it doesn't work you need to install numpy
import numpy as np

docs_array = np.array(content, dtype='object')

v1 = np.array(doc_term_matrix['the'])    
v2 = np.array(doc_term_matrix['document'])

print(v1)
print(v2)
print('-------')

# find the documents that have both terms from v1 and v2
v3 = v1 | v2

print(v3)

# display the content document from the result
[doc for doc in v3 * docs_array if doc]

[1 0 0]
[1 1 1]
-------
[1 1 1]


['This is the first document. It contains some words.',
 'The second document is a bit longer and has different words.',
 'The third document is short. Short documents can be concise.']